operator:
  enabled: true
  deployment:
    imagePullPolicy: Always
    image: "registry.gitlab.com/georgeraven/authentik-manager:latest"
    name: authentik-manager
    replicas: 3
    env: # statically defined environment variables can be as many as desired
    - name: LEADER_ELECT
      value: "true"
  ports: []
  # - name: http
  #   containerPort: 9000
  #   servicePort: 80
  #   protocol: TCP
  labels:
  - key: type
    value: auth
  - key: app
    value: authentik-manager
  serviceAccount:
    enabled: true
    name: authentik-manager
    generate: true
  clusterRole:
    enabled: true
    name: authentik-manager
    generate: true
  clusterRoleBinding:
    enabled: true
    name: authentik-manager
    generate: true
  role:
    enabled: true
    name: authentik-manager
    generate: true
  roleBinding:
    enabled: true
    name: authentik-manager
    generate: true
