# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: app-blueprint
entries:
- model: authentik_core.application
  #id: null
  identifiers:
    #pk: c885d2bd-1ebd-4799-9dfa-40d87f644fca
    slug: {{ .slug }}
  state: present
  attrs:
    name: {{ .name }} # MyApplication
    group: {{ .group }} # my-group
    policy_engine_mode: {{ .policy_engine_mode }} # any
    provider: {{ .provider }} # 2
    slug: {{ .slug }} # my-application
  conditions: []
