{{- if .Values.authentik.enabled }}
{{- $akouter := . }}
{{- $aktypes := list "server" "worker" }}
{{- range $aktypes }}
{{- $aktype := . }}
{{- with $akouter }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-{{ $aktype }}
  labels:
    {{- include "ak.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $aktype }}
    app.kubernetes.io/part-of: authentik
    {{- range .Values.authentik.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
spec:
  replicas: {{ .Values.authentik.deployment.replicas }}
  selector:
    matchLabels:
      mode: {{ $aktype }}
      {{- range .Values.authentik.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "ak.labels" . | nindent 8 }}
        mode: {{ $aktype }}
        app.kubernetes.io/component: {{ $aktype }}
        app.kubernetes.io/part-of: authentik
        {{- range .Values.authentik.labels }}
        {{ .key }}: {{ .value }}
        {{- end }}
    spec:
      containers:
        - name: authentik-{{ $aktype }}
          image: "{{ .Values.authentik.image.registry }}/{{ .Values.authentik.image.repository}}:{{ .Values.authentik.image.tag}}"
          imagePullPolicy: {{ .Values.authentik.deployment.imagePullPolicy }}
          args:
          - |-
            {{ $aktype }}
          ports:
            {{- range .Values.authentik.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          env:
            # https://goauthentik.io/docs/installation/configuration
            # POSTGRESQL AUTOGEN VARIABLES
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: {{ .Values.postgresql.fullnameOverride }}-hl
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: {{ .Values.postgresql.auth.database }}
            - name: AUTHENTIK_POSTGRESQL__USER
              value: {{ .Values.postgresql.auth.username }}
            - name: AUTHENTIK_POSTGRESQL__PORT
              value: {{ .Values.postgresql.postgresql.service.ports.postgresql | quote }}
            # REDIS AUTOGEN VARIABLES
            - name: AUTHENTIK_REDIS__HOST
              value: {{ .Values.redis.fullnameOverride }}-master
            - name: AUTHENTIK_REDIS__PORT
              value: {{ .Values.redis.master.service.ports.redis | quote }}
            # SMTP AUTOGEN VARIABLES
            - name: AUTHENTIK_EMAIL__HOST
              value: {{ .Values.smtp.host }}
            - name: AUTHENTIK_EMAIL__PORT
              value: {{ .Values.smtp.port | quote }}
            - name: AUTHENTIK_EMAIL__USERNAME
              value: {{ .Values.smtp.username }}
            # AUTHENTIK AUTOGEN VARIABLES
            - name: AUTHENTIK_COOKIE_DOMAIN
              value: {{ .Values.global.domain.full }}
            # additional static deployment env variables
            {{- range .Values.authentik.deployment.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            # env paths pointing to mounted secrets
            {{- range .Values.authentik.secrets.lookup }}
            - name: {{ .env }}
              value: {{ printf "file://%s/%s" $.Values.authentik.secrets.basePath .file }}
            {{- end }}

          {{- if eq $aktype "worker"}}
          {{- else }}
          startupProbe:
            httpGet:
              path: /-/health/live/
              port: {{ (first .Values.authentik.ports).name }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /-/health/live/
              port: {{ (first .Values.authentik.ports).name }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/health/ready/
              port: {{ (first .Values.authentik.ports).name }}
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          volumeMounts:
          # config mount
          # authentik does not use a standard config so this does nothing
          - mountPath:  {{ .Values.authentik.config.path | quote }}
            name: config
            readOnly: true
          # secrets mount
          - mountPath: {{ .Values.authentik.secrets.basePath | quote }}
            name: secrets
            readOnly: true
          {{- if eq $aktype "worker"}}
          {{- range .Values.authentik.blueprints }}
          # single key mount as single file for file-based blueprint
          # https://stackoverflow.com/a/49155527
          - mountPath: {{ .dest }}
            name: {{ .name }}
            subPath: {{ .configMap.key }}
          {{- end }}
          {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ .Values.authentik.config.name }}
      - name: secrets
        secret:
          secretName: {{ .Values.secret.name }}
          optional: false
          items:
          {{- range .Values.authentik.secrets.lookup }}
          - key: {{ .key }}
            path: {{ .file }}
          {{- end }}
      {{- if eq $aktype "worker"}}
      {{- range .Values.authentik.blueprints }}
      # single key mount as single file for file-based blueprint
      # https://stackoverflow.com/a/49155527
      - name: {{ .name }}
        configMap:
          name: {{ .configMap.name }}
          items:
          - key: {{ .configMap.key }}
            path: {{ .configMap.key }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
