{{ if .Values.authentik.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authentik.service.name | lower | quote }}
  labels:
    {{- range .Values.authentik.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- range .Values.authentik.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
  ports:
    {{- range .Values.authentik.ports }}
    - protocol: {{ .protocol }}
      port: {{ .servicePort }} # services in-cluster port
      targetPort: {{ .containerPort }} # port of container/ pod
      name: {{ .name }}
    {{- end }}
{{- end }}
