apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authentik-netpol
spec:
  podSelector:
    matchLabels:
      {{- range .Values.authentik.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  policyTypes:
  - Egress
  egress:
  - to:
    # allow to go to WAN internet
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/20
    # or allowed to go to local namespace
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
  # Also
  - to:
    # allow DNS lookups
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    # on specific ports
    ports:
    - protocol: UDP
      port: 53
