{{ if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgadmin.deployment.name | lower | quote }}
  labels:
    {{- include "ak.labels" . | nindent 4 }}
    {{- range .Values.pgadmin.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
spec:
  replicas: {{ .Values.pgadmin.deployment.replicas }}
  selector:
    matchLabels:
      {{- range .Values.pgadmin.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "ak.labels" . | nindent 8 }}
        {{- range .Values.pgadmin.labels }}
        {{ .key }}: {{ .value }}
        {{- end }}
    spec:
      # TODO: Create init container to generate from env variables the pgpass file
      # https://www.postgresql.org/docs/9.1/libpq-pgpass.html
      # This init container should generate a file in the following format:
      # hostname:port:database:username:password
      # The weakness of this approach is it less dynamic and requires the deployment to be restarted
      # however the awkwardness of the format also including semi-dynamic variables makes this a necessary evil
      # databases dont tend to rapidly change credentials so this should be almost never incurred.
      containers:
        - name: pgadmin
          image: "{{ .Values.pgadmin.image.registry }}/{{ .Values.pgadmin.image.repository}}:{{ .Values.pgadmin.image.tag}}"
          imagePullPolicy: {{ .Values.pgadmin.deployment.imagePullPolicy }}
          ports:
            {{- range .Values.pgadmin.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          env:
            {{- range .Values.pgadmin.deployment.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.pgadmin.secrets }}
            {{- $secretContext := . }}
            {{- range .lookup }}
            - name: {{ .env }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretContext.name }}
                  key: {{ .key }}
                  optional: false
            {{- end }}
            {{- end }}
          volumeMounts:
          - name: servers-config
            mountPath: {{ .Values.pgadmin.servers.path }}
            subPath: {{ .Values.pgadmin.servers.key }}
      {{- if .Values.pgadmin.persistence.enabled }}
          - mountPath: "/var/lib/pgadmin/data"
            name: data
      {{- end }}
      volumes:
      - name: servers-config
        configMap:
          name: {{ .Values.pgadmin.config.name }}
          items:
          - key: {{ .Values.pgadmin.servers.key }}
            path: {{ .Values.pgadmin.servers.key }}
      {{- if .Values.pgadmin.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.pgadmin.persistence.name | lower | quote }}
      {{- end }}
{{ end }}
