{{- if .Values.authentik.enabled }}
{{- $akouter := . }}
{{- $aktypes := list "server" "worker" }}
{{- range $aktypes }}
{{- $aktype := . }}
{{- with $akouter }}
---
# {{ $aktype }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authentik.service.name }}-{{ $aktype }}
  labels:
    {{- include "ak.labels" . | nindent 4 }}
    mode: {{ $aktype }}
    {{- range .Values.authentik.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    mode: {{ $aktype }}
    {{- range .Values.authentik.labels }}
    {{ .key }}: {{ .value }}
    {{- end }}
  ports:
    {{- range .Values.authentik.ports }}
    - protocol: {{ .protocol }}
      port: {{ .servicePort }} # services in-cluster port
      targetPort: {{ .containerPort }} # port of container/ pod
      name: {{ .name }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
