{{- if .Values.authentik.enabled }}
{{- $akouter := . }}
{{- $aktypes := list "server" "worker" }}
{{- range $aktypes }}
{{- $aktype := . }}
{{- with $akouter }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authentik-{{ $aktype }}
spec:
  podSelector:
    matchLabels:
      mode: {{ $aktype }}
      {{- range .Values.authentik.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  policyTypes:
  - Egress
  - Ingress
  {{- if eq $aktype "server"}}
  ingress:
  - {}
  #- from:
  #  # allow ingress from other pods in this namespace
  #  - namespaceSelector:
  #      matchLabels:
  #        kubernetes.io/metadata.name: {{ .Release.Namespace }}
  #  # to specific ports by name
  #  ports:
  #  - protocol: TCP
  #    port: http
  #  - protocol: TCP
  #    port: https
  #  - protocol: TCP
  #    port: metrics
  {{- end }}
  egress:
  - to:
    # allow to go to WAN internet
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/20
    # or allowed to go to local namespace
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
  # Also
  - to:
    # allow DNS lookups
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    # on specific ports
    ports:
    - protocol: UDP
      port: 53
{{- end }}
{{- end }}
{{- end }}
