apiVersion: sso.goauthentik.io/v1alpha1
kind: AkProvider
metadata:
  labels:
    app.kubernetes.io/name: akprovider
    app.kubernetes.io/instance: akprovider-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: akprovider-sample
spec:
  # TODO(user): Add fields here
