{{- if .Values.authentik.customCss.enabled }}
{{- if .Values.authentik.customCss.generate }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.authentik.customCss.configMap.name }}
data:
  {{ .Values.authentik.customCss.configMap.key }}: |
    /* Custom CSS */
    /* this file should be mounted to /web/dist/custom.css in the authentik server */
    /* Example custom CSS you can use your own in the helm chart / operator values */
    {{ .Values.authentik.customCss.css | nindent 4 }}
{{- end }}
{{- end }}
