# permissions for end users to view akblueprints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: akblueprint-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: akblueprint-viewer-role
rules:
- apiGroups:
  - akm.goauthentik.io
  resources:
  - akblueprints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - akm.goauthentik.io
  resources:
  - akblueprints/status
  verbs:
  - get
