# permissions for end users to view akproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: akprovider-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: akprovider-viewer-role
rules:
- apiGroups:
  - sso.goauthentik.io
  resources:
  - akproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sso.goauthentik.io
  resources:
  - akproviders/status
  verbs:
  - get
