# permissions for end users to view oidcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: oidc-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: oidc-viewer-role
rules:
- apiGroups:
  - akm.goauthentik.io
  resources:
  - oidcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - akm.goauthentik.io
  resources:
  - oidcs/status
  verbs:
  - get
