---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - akm.goauthentik.io
  resources:
  - akblueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akm.goauthentik.io
  resources:
  - akblueprints/finalizers
  verbs:
  - update
- apiGroups:
  - akm.goauthentik.io
  resources:
  - akblueprints/status
  verbs:
  - get
  - patch
  - update
