---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - akm.goauthentik.io
  resources:
  - aks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akm.goauthentik.io
  resources:
  - aks/finalizers
  verbs:
  - update
- apiGroups:
  - akm.goauthentik.io
  resources:
  - aks/status
  verbs:
  - get
  - patch
  - update
