# A namespaced role to allow our opertor full control of its specific namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.operator.role.name }}
  labels:
    {{- include "akm.labels" . | nindent 4 }}
rules:
# do anything with namespaced resources in our own namespace
# excludes the ability to modify roles, service accounts, and bindings for obvious reasons

- apiGroups:
  - ""
  resources:
  - bindings
  - configmaps
  - endpoints
  - events
  - limitranges
  - persistentvolumeclaims
  - pods
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - secrets
  - services
  verbs:
  - "*"

# The bitnami helm charts create service accounts in this namespace
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - "*"

- apiGroups:
  - apps
  - batch
  resources:
  - "*"
  verbs:
  - "*"

- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - "*"

- apiGroups:
  - batch/v1
  resources:
  - "*"
  verbs:
  - "*"

- apiGroups:
  - discovery.k8s.io
  resources:
  - "*"
  verbs:
  - "*"

- apiGroups:
  - events.k8s.io
  resources:
  - "*"
  verbs:
  - "*"

- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - "*"

- apiGroups:
  - policy
  resources:
  - "*"
  verbs:
  - "*"

- apiGroups:
  - akm.goauthentik.io
  resources:
  - "*"
  verbs:
  - "*"
