# ClusterRole to watch for our CRDs and the respective ingress modified in the CRDs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operator.clusterRole.name }}
rules:

- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - "*"

# # List configmaps and secrets
# # Operator SDK insists on this apparently
# # TODO: check why operator-SDK insists on this permission
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - "*"
  #- list
  #- watch

# - apiGroups:
#   - "apps"
#   resources:
#   - deployments
#   verbs:
#   - list
#   - watch

- apiGroups:
  - akm.goauthentik.io
  resources:
  - "*"
  verbs:
  - "*"

# # BREAK GLASS in case of debug
# - apiGroups:
#   # all api groups
#   - "*"
#   resources:
#   # all resources
#   - "*"
#   verbs:
#   # do anything
#   - "*"
