apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.operator.roleBinding.name }}
  labels:
    {{- include "akm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.operator.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.operator.role.name }}
  # apiGroup: rbac.authorization.k8s.io
