apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: operator-netpol
  labels:
    {{- include "akm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- range .Values.operator.labels }}
      {{ .key }}: {{ .value }}
      {{- end }}
  egress:
  - {}
  policyTypes:
  - Egress
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: operator-netpol
#spec:
#  podSelector:
#    matchLabels:
#      {{- range .Values.operator.labels }}
#      {{ .key }}: {{ .value }}
#      {{- end }}
#  policyTypes:
#  - Ingress
#  - Egress
#  egress: {}
  #- to:
  #  # allowed to go to local namespace
  #  - namespaceSelector:
  #      matchLabels:
  #        kubernetes.io/metadata.name: {{ .Release.Namespace }}
  ## Also
  #- to:
  #  # allow lookups to kube system
  #  - namespaceSelector:
  #      matchLabels:
  #        kubernetes.io/metadata.name: kube-system
  ## Also
  #- to:
  #  # allow to communicate to kube-api default service
  #  - namespaceSelector:
  #      matchLabels:
  #        kubernetes.io/metadata.name: default
  #  # # on specific ports for DNS
  #  # ports:
  #  # - protocol: UDP
  #  #   port: 53
