# A namespaced role to allow our opertor full control of its specific namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.operator.role.name }}
rules:
- apiGroups:
  - "*"
  resources:
  - "configmaps"
  - "pods"
  - "secrets"
  - "services"
  - "horizontalpodautoscalers"
  - "jobs"
  - "cronjobs"
  - "ingress"
  - "networkpolicies"
  - "deployments"
  verbs:
  - "*"
- apiGroups:
  - "akm.goauthentik.io"
  resources:
  - "*"
  verbs:
  - "*"
