apiVersion: akm.goauthentik.io/v1alpha1
kind: Ak
metadata:
  labels:
    app.kubernetes.io/name: ak
    app.kubernetes.io/instance: akm
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: ak
  namespace: auth
spec:
  values:
    # Any child of values is taken to mean helm values for the underlying Ak helm chart
    # You may override some or all of the fields.
    # Please see chars/operator/ak/values.yaml for possible overrides
    # https://gitlab.com/GeorgeRaven/authentik-manager/-/blob/master/charts/ak/values.yaml
    # Following are some basic overrides that you should consider
    global:
      domain:
        base: org.example
        full: auth.org.example
    smtp:
      enabled: false
      port: 587
      host: smtp.gmail.com
      from: noreply@org.example
    secret:
      # disabled here to allow you to load your own secret that you should definately have backed up
      generate: false
      randLength: 30
      # you probably dont want to change this name as you will have to change
      # it everywhere in subcharts
      name: auth
