apiVersion: akm.goauthentik.io/v1alpha1
kind: AkBlueprint
metadata:
  labels:
    app.kubernetes.io/name: akblueprint
    app.kubernetes.io/instance: akm
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: auth-application
  namespace: auth
spec:
  file: /blueprints/operator/my-oidc-app.yaml
  blueprint: |
    version: 1
    metadata:
      name: my-oidc-app
    entries:
    - model: authentik_core.application
      #id: null
      identifiers:
        #pk: c885d2bd-1ebd-4799-9dfa-40d87f644fca
        slug: my-oidc-app
      state: present
      attrs:
        name: My OIDC App # MyApplication
        group: some-group # my-group
        policy_engine_mode: any # any
        #provider: {{ .provider }} # 2
        #provider: !Find [authentik_flows.flow, [id, my-oidc-provider ]] # 2
        slug: my-oidc-app # my-application
      conditions: []
