apiVersion: akm.goauthentik.io/v1alpha1
kind: OIDC
metadata:
  labels:
    app.kubernetes.io/name: oidc
    app.kubernetes.io/instance: auth
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: oidc-sample
  namespace: default
spec:
  domains:
  - someapp.org.example
