apiVersion: akm.goauthentik.io/v1alpha1
kind: AkBlueprint
metadata:
  labels:
    app.kubernetes.io/name: akblueprint
    app.kubernetes.io/instance: akm
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: my-oidc-app
  namespace: auth
spec:
  file: /blueprints/operator/my-oidc-app.yaml
  blueprint: |
    version: 1
    metadata:
      name: my-oidc-app
    entries:
    - model: authentik_core.application
      #id: null
      identifiers:
        slug: my-oidc-app
      state: present
      attrs:
        name: My OIDC App
        group: some-group
        policy_engine_mode: any
        provider: !Find [authentik_providers_oauth2.oauth2provider, [name, my-oidc-provider ]]
        slug: my-oidc-app
      conditions: []
